### ISSUE TITLE
Icons for points

### ISSUE THREAD

**Issue by vrautenbach** [geo-classroom/daily-rainfall#19]
The normal pin is not my favourite. Below are two options I created on Icon8 (https://icons8.com). 

This would be an option for SAWS
![icons8-moderate-rain-60](https://user-images.githubusercontent.com/7597595/180414821-ee560d46-5af7-4be0-95b2-b53965932cb2.png)

And this for user data
![icons8-netatmo-rain-module-50](https://user-images.githubusercontent.com/7597595/180414886-45e818be-0143-4760-961a-732dfb9406c6.png)

Not sure if it is the best, maybe will give you some ideas.

**Comment by Riley-5** [comment]
![image](https://user-images.githubusercontent.com/63784083/180651041-d20e8895-4c53-4794-8f06-5d271c83bcfc.png)


Styling with the Proposed icons
